USE [master]
GO
/****** Object:  Database [FooKit] ******/
CREATE DATABASE [FooKit]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FooKit] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FooKit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FooKit] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FooKit] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FooKit] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FooKit] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FooKit] SET ARITHABORT OFF 
GO
ALTER DATABASE [FooKit] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FooKit] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FooKit] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FooKit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FooKit] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FooKit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FooKit] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FooKit] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FooKit] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FooKit] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FooKit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FooKit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FooKit] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FooKit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FooKit] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FooKit] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [FooKit] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FooKit] SET RECOVERY FULL 
GO
ALTER DATABASE [FooKit] SET  MULTI_USER 
GO
ALTER DATABASE [FooKit] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FooKit] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FooKit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FooKit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FooKit] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FooKit] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FooKit', N'ON'
GO
ALTER DATABASE [FooKit] SET QUERY_STORE = ON
GO
ALTER DATABASE [FooKit] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FooKit]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RefreshTokens] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RefreshTokens](
	[Id] [uniqueidentifier] NOT NULL,
	[Token] [nvarchar](200) NOT NULL,
	[AddedDate] [datetime2](7) NOT NULL,
	[ExpiryDate] [datetime2](7) NOT NULL,
	[IsRevoked] [bit] NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_RefreshTokens] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserLogins] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserLogins](
	[LoginProvider] [nvarchar](128) NOT NULL,
	[ProviderKey] [nvarchar](256) NOT NULL,
	[ProviderDisplayName] [nvarchar](128) NULL,
	[UserId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_UserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [uniqueidentifier] NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](255) NULL,
	[Email] [nvarchar](256) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20260424033205_InitialCreate', N'9.0.15')
GO
INSERT [dbo].[RefreshTokens] ([Id], [Token], [AddedDate], [ExpiryDate], [IsRevoked], [UserId]) VALUES (N'c8643c7b-25e3-44cf-9a5b-645850f9f538', N'/OrGZFF2+TjeBRU8Obg7750jgzWjgovLpzZGrkoXCKXG3re8xVhQpea1B7t1DBeV7jWJ4lNP+VXZuyhKSuOHKQ==', CAST(N'2026-04-24T04:02:08.0051731' AS DateTime2), CAST(N'2026-05-01T04:02:08.0051734' AS DateTime2), 0, N'5191a820-c43d-4a37-bf69-2ea5cfed4e69')
INSERT [dbo].[RefreshTokens] ([Id], [Token], [AddedDate], [ExpiryDate], [IsRevoked], [UserId]) VALUES (N'b525240c-a57c-4c60-9984-69ea33e2b7b9', N'dnXqquL7pvvStRzuN+Tdl80RbTNjJ8z9cb51o5NpeiRp6ByHQdAFC71iLk/sBrhwrOkSsQGa45rXX246WOMp4g==', CAST(N'2026-04-24T03:58:16.7569871' AS DateTime2), CAST(N'2026-05-01T03:58:16.7570737' AS DateTime2), 0, N'5191a820-c43d-4a37-bf69-2ea5cfed4e69')
INSERT [dbo].[RefreshTokens] ([Id], [Token], [AddedDate], [ExpiryDate], [IsRevoked], [UserId]) VALUES (N'784df542-1464-492c-8a6d-8cfd6e0b7cd1', N'72SLHlDhhPs6eH67ZFXdChqlrea96hdOxuK+nmTg7s01AUO5GyN52hPa1qNdXp6Ube02mv3cQKpfRvXeqm+Huw==', CAST(N'2026-04-24T03:58:32.6849829' AS DateTime2), CAST(N'2026-05-01T03:58:32.6849838' AS DateTime2), 0, N'5191a820-c43d-4a37-bf69-2ea5cfed4e69')
INSERT [dbo].[RefreshTokens] ([Id], [Token], [AddedDate], [ExpiryDate], [IsRevoked], [UserId]) VALUES (N'80de42da-6143-40b4-b36a-b951b117eaa2', N'pkppXcNog74gdOTjepP53zlPlLAbkM87D3QVN1IUeguHwaeLndcxRhiDRVmd1adT7a05lTgOEBJMJRhQifg86w==', CAST(N'2026-04-24T03:58:37.8378327' AS DateTime2), CAST(N'2026-05-01T03:58:37.8378330' AS DateTime2), 0, N'5191a820-c43d-4a37-bf69-2ea5cfed4e69')
GO
INSERT [dbo].[UserLogins] ([LoginProvider], [ProviderKey], [ProviderDisplayName], [UserId]) VALUES (N'Google', N'113999591533964420241', N'Google', N'5191a820-c43d-4a37-bf69-2ea5cfed4e69')
GO
INSERT [dbo].[Users] ([Id], [Username], [PasswordHash], [Email]) VALUES (N'5191a820-c43d-4a37-bf69-2ea5cfed4e69', N'nguyenvana', N'$2a$12$fggCzKZcOsxFOdGIacUc5OUG0RpPJUeys6xrdp7Ohh0TMPoRQng72', N'satruong14@gmail.com')
GO
/****** Object:  Index [IX_RefreshTokens_UserId] ******/
CREATE NONCLUSTERED INDEX [IX_RefreshTokens_UserId] ON [dbo].[RefreshTokens]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserLogins_UserId] ******/
CREATE NONCLUSTERED INDEX [IX_UserLogins_UserId] ON [dbo].[UserLogins]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Users_Email] ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Users_Email] ON [dbo].[Users]
(
	[Email] ASC
)
WHERE ([Email] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Users_Username] ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Users_Username] ON [dbo].[Users]
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RefreshTokens]  WITH CHECK ADD  CONSTRAINT [FK_RefreshTokens_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RefreshTokens] CHECK CONSTRAINT [FK_RefreshTokens_Users_UserId]
GO
ALTER TABLE [dbo].[UserLogins]  WITH CHECK ADD  CONSTRAINT [FK_UserLogins_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserLogins] CHECK CONSTRAINT [FK_UserLogins_Users_UserId]
GO
USE [master]
GO
ALTER DATABASE [FooKit] SET  READ_WRITE 
GO
